
services:

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: warehouse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_pipeline_net

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - data_pipeline_net

  createbuckets:
    image: minio/mc:latest
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 20;
      mc alias set local http://minio:9000 minioadmin minioadmin123;
      mc mb local/bronze --ignore-existing;
      mc mb local/silver --ignore-existing;
      mc mb local/gold --ignore-existing;
      exit 0;
      "
    networks:
      - data_pipeline_net

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./jobs:/opt/spark/jobs
    networks:
      - data_pipeline_net

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./jobs:/opt/spark/jobs
    networks:
      - data_pipeline_net

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@postgres:5432/warehouse
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - data_pipeline_net

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
    command: airflow webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@postgres:5432/warehouse
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./jobs:/opt/airflow/jobs
    networks:
      - data_pipeline_net

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    command: airflow scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@postgres:5432/warehouse
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./jobs:/opt/airflow/jobs
    networks:
      - data_pipeline_net

  streamlit:
    image: python:3.11-slim
    container_name: streamlit
    working_dir: /app
    volumes:
      - ./streamlit:/app
    command: >
      bash -c "
      pip install streamlit pandas psycopg2-binary &&
      streamlit run app.py --server.address=0.0.0.0
      "
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    networks:
      - data_pipeline_net

volumes:
  postgres_data:
  minio_data:

networks:
  data_pipeline_net:
    driver: bridge